name: Release

# on:
#   workflow_dispatch:

on:
  push:
    branches:
      - main

jobs:
  release:

    permissions:
      contents: write        # to be able to publish a GitHub release
      issues: write          # to be able to comment on released issues
      pull-requests: write   # to be able to comment on released pull requests

    runs-on: ubuntu-latest
    environment: release
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install plugins
        run: npm install @semantic-release/git @semantic-release/changelog conventional-changelog-conventionalcommits -D

      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # DOCKER_USERNAME: gilmrt
          # DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
